### ISSUE TITLE
Rethink -> Mongo/SQL

### ISSUE THREAD

**Issue by jjwedemyer** [Mindful-Meerkats/json-api#2]
Got to decide if it's suitable to create a datastructure in $SQL-database or go with document store in MongoDB.

**Comment by RamonGebben** [comment]
Why do you think this would be needed?

**Comment by jjwedemyer** [comment]
On one hand, Relational Database would make data checks in the API handler mostly obsolete and would improve the data consistency.
On the other hand, Mongo has this feature with the validator flag on creating tables, while not providing JOINs directly (which would be considered the most important thing about Relational DBS)
I don't know what the reasons are to choosing RethinkDB in the first place, all I can tell that it puts more load on the dev to actually make sure you serve the right type of data.

**Comment by jjwedemyer** [comment]
I mean of course for prototyping and first testing it can be great to have a flexible layout, but later on for production i'd say a relational DBS would give the option to clean up a lot of the code base and as stated above give consistency throughout

**Comment by RamonGebben** [comment]
Ok valid points. What is a problem with Mongo is that when you'll need to scale, you're going to have a bad time. And the performance of Mongo will quickly decrease when doing more complex queries which I can imagine you'd want to do over time.

RethinkDB has a better perfomance reputation and an amazing feature of them is the change feed api which allow you to quicker respond to User behavior.

It's your call, just some things to keep in mind.

**Comment by jjwedemyer** [comment]
The change from being developed by a company to being opensourced somehow scared me (RethinkDB that is), will wait a little on deciding this.
I will develop the SQL scheme anyways as most of the relations are better there, but it's rather hard to switch up tables there 👍
